# fly.toml app configuration file generated for twitch-integrations on 2023-12-02T22:18:02-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "twitch-integrations"
primary_region = "ord"

[build]

[mounts]
  source = "nix_timer"
  destination = "/data/nix_timer"
  processes = ["app"]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
